name: 'Amplify PR Merged'
on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Prod
        if: contains(github.event.pull_request.labels.*.name, 'Deploy to production')
        uses: yinlinchen/amplify-preview-actions@master
        with:
          branch_name: master
          amplify_command: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AmplifyAppId: ${{ secrets.AmplifyAppId }}
          AWS_REGION: 'us-east-1'    
